# Generated by Django 4.0.6 on 2022-07-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('card_set', models.CharField(choices=[('ATK', 'Attacks'), ('SPE', 'Spells'), ('MOV', 'Movement'), ('ITM', 'Items'), ('CLS', 'Class Features')], default='ATK', max_length=3)),
            ],
        ),
    ]
