# Generated by Django 4.0.6 on 2022-07-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_set',
            field=models.CharField(choices=[('ATK', 'Attacks'), ('SPE', 'Spells'), ('MOV', 'Movement'), ('ITE', 'Items'), ('CLS', 'Class Features')], default='ATK', max_length=3),
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('cards', models.ManyToManyField(to='Cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('decks', models.ManyToManyField(to='Cards.deck')),
            ],
        ),
    ]
